In [4]:
# !pip install tqdm
import pandas as pd
import os
import json
from tqdm import tqdm

In [5]:
filenames = []
for file in os.listdir('/Users/karnayak/Personal/cricket_mlops/data/ipl_json'):
    filenames.append(os.path.join('/Users/karnayak/Personal/cricket_mlops/data/ipl_json', file))

In [6]:
final_df = pd.DataFrame()
counter = 1
for file in tqdm(filenames):
    with open(file, 'r') as f:
        df = pd.json_normalize(json.load(f))
        df['match_id'] = counter
        final_df = pd.concat([final_df, df], ignore_index=True)
        counter+=1
        
final_df

100%|██████████| 1233/1233 [00:36<00:00, 33.38it/s]

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.event.name,info.event.match_number,info.gender,...,info.registry.people.DAJ Bracewell,info.registry.people.Shivam Singh,info.registry.people.IC Porel,info.registry.people.RV Pawar,info.registry.people.T Mishra,info.registry.people.Gurnoor Brar,info.registry.people.BJ Dwarshuis,info.registry.people.KS Rathore,info.registry.people.Subhransu Senapati,info.registry.people.S Midhun
0,"[{'team': 'Sunrisers Hyderabad', 'overs': [{'o...",1.1.0,2024-04-09,1,6,Mohali,[2024-04-09],Indian Premier League,23.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'team': 'Chennai Super Kings', 'overs': [{'o...",1.1.0,2023-04-26,1,6,Kolkata,[2023-04-23],Indian Premier League,33.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'team': 'Rajasthan Royals', 'overs': [{'over...",1.0.0,2011-05-02,2,6,Kimberley,[2009-05-09],Indian Premier League,37.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'team': 'Mumbai Indians', 'overs': [{'over':...",1.1.0,2021-10-02,2,6,Sharjah,[2021-10-02],Indian Premier League,46.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'team': 'Mumbai Indians', 'overs': [{'over':...",1.0.0,2015-05-19,1,6,Mumbai,[2015-05-19],Indian Premier League,NaN,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228,"[{'team': 'Royal Challengers Bangalore', 'over...",1.0.0,2020-10-10,1,6,NaN,[2020-10-10],Indian Premier League,25.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1229,"[{'team': 'Rajasthan Royals', 'overs': [{'over...",1.0.0,2019-04-16,2,6,Jaipur,[2019-04-07],Indian Premier League,21.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ade90de7
1230,"[{'team': 'Royal Challengers Bangalore', 'over...",1.0.0,2013-04-13,2,6,Chennai,[2013-04-13],Indian Premier League,16.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1231,"[{'team': 'Delhi Daredevils', 'overs': [{'over...",1.0.0,2019-04-19,1,6,Hyderabad,[2018-05-05],Indian Premier League,36.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1232,"[{'team': 'Chennai Super Kings', 'overs': [{'o...",1.1.0,2025-04-30,1,6,Chennai,[2025-04-30],Indian Premier League,49.0,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
backup = final_df.copy()

In [8]:
final_df = backup.copy()

In [9]:
final_df.columns.to_list()

['innings',
 'meta.data_version',
 'meta.created',
 'meta.revision',
 'info.balls_per_over',
 'info.city',
 'info.dates',
 'info.event.name',
 'info.event.match_number',
 'info.gender',
 'info.match_type',
 'info.officials.match_referees',
 'info.officials.reserve_umpires',
 'info.officials.tv_umpires',
 'info.officials.umpires',
 'info.outcome.winner',
 'info.outcome.by.runs',
 'info.overs',
 'info.player_of_match',
 'info.players.Sunrisers Hyderabad',
 'info.players.Punjab Kings',
 'info.registry.people.AG Wharf',
 'info.registry.people.AK Markram',
 'info.registry.people.Abdul Samad',
 'info.registry.people.Abhishek Sharma',
 'info.registry.people.Arshdeep Singh',
 'info.registry.people.Ashutosh Sharma',
 'info.registry.people.B Kumar',
 'info.registry.people.H Klaasen',
 'info.registry.people.HV Patel',
 'info.registry.people.Harpreet Brar',
 'info.registry.people.JD Unadkat',
 'info.registry.people.JM Bairstow',
 'info.registry.people.JM Sharma',
 'info.registry.people.K Rabada',
 'info.registry.people.NA Patwardhan',
 'info.registry.people.Navdeep Singh',
 'info.registry.people.Nithish Kumar Reddy',
 'info.registry.people.P Simran Singh',
 'info.registry.people.PJ Cummins',
 'info.registry.people.PM Joshi',
 'info.registry.people.RA Tripathi',
 'info.registry.people.S Dhawan',
 'info.registry.people.SM Curran',
 'info.registry.people.Shahbaz Ahmed',
 'info.registry.people.Shashank Singh',
 'info.registry.people.Sikandar Raza',
 'info.registry.people.T Natarajan',
 'info.registry.people.TM Head',
 'info.registry.people.V Narayan Kutty',
 'info.season',
 'info.team_type',
 'info.teams',
 'info.toss.decision',
 'info.toss.winner',
 'info.venue',
 'match_id',
 'info.players.Chennai Super Kings',
 'info.players.Kolkata Knight Riders',
 'info.registry.people.A Bengeri',
 'info.registry.people.AD Russell',
 'info.registry.people.AM Rahane',
 'info.registry.people.AT Rayudu',
 'info.registry.people.Akash Singh',
 'info.registry.people.CV Varun',
 'info.registry.people.D Wiese',
 'info.registry.people.DP Conway',
 'info.registry.people.JJ Roy',
 'info.registry.people.K Khejroliya',
 'info.registry.people.M Pathirana',
 'info.registry.people.M Theekshana',
 'info.registry.people.MM Ali',
 'info.registry.people.MS Dhoni',
 'info.registry.people.N Jagadeesan',
 'info.registry.people.N Rana',
 'info.registry.people.Nitin Menon',
 'info.registry.people.RA Jadeja',
 'info.registry.people.RD Gaikwad',
 'info.registry.people.RK Singh',
 'info.registry.people.S Dube',
 'info.registry.people.SP Narine',
 'info.registry.people.Shakti Singh',
 'info.registry.people.Suyash Sharma',
 'info.registry.people.TU Deshpande',
 'info.registry.people.Tapan Sharma',
 'info.registry.people.UT Yadav',
 'info.registry.people.VK Sharma',
 'info.registry.people.VR Iyer',
 'info.outcome.by.wickets',
 'info.players.Rajasthan Royals',
 'info.registry.people.A Singh',
 'info.registry.people.AM Saheba',
 'info.registry.people.AS Raut',
 'info.registry.people.GAV Baxter',
 'info.registry.people.GC Smith',
 'info.registry.people.HDPK Dharmasena',
 'info.registry.people.J Srinath',
 'info.registry.people.JA Morkel',
 'info.registry.people.JDP Oram',
 'info.registry.people.KH Hurter',
 'info.registry.people.L Balaji',
 'info.registry.people.LA Carseldine',
 'info.registry.people.M Muralitharan',
 'info.registry.people.M Vijay',
 'info.registry.people.ML Hayden',
 'info.registry.people.NV Ojha',
 'info.registry.people.S Badrinath',
 'info.registry.people.S Tyagi',
 'info.registry.people.SA Asnodkar',
 'info.registry.people.SB Jakati',
 'info.registry.people.SK Raina',
 'info.registry.people.SK Trivedi',
 'info.registry.people.SK Warne',
 'info.registry.people.SM Harwood',
 'info.registry.people.YK Pathan',
 'info.players.Mumbai Indians',
 'info.players.Delhi Capitals',
 'info.registry.people.A Nortje',
 'info.registry.people.AK Chaudhary',
 'info.registry.people.AR Patel',
 'info.registry.people.Avesh Khan',
 'info.registry.people.HH Pandya',
 'info.registry.people.J Yadav',
 'info.registry.people.JJ Bumrah',
 'info.registry.people.KA Pollard',
 'info.registry.people.KH Pandya',
 'info.registry.people.MA Gough',
 'info.registry.people.NM Coulter-Nile',
 'info.registry.people.PP Shaw',
 'info.registry.people.Q de Kock',
 'info.registry.people.R Ashwin',
 'info.registry.people.RG Sharma',
 'info.registry.people.RR Pant',
 'info.registry.people.SA Yadav',
 'info.registry.people.SO Hetmyer',
 'info.registry.people.SPD Smith',
 'info.registry.people.SS Iyer',
 'info.registry.people.SS Tiwary',
 'info.registry.people.TA Boult',
 'info.event.stage',
 'info.registry.people.A Nehra',
 'info.registry.people.CK Nandan',
 'info.registry.people.DJ Bravo',
 'info.registry.people.DR Smith',
 'info.registry.people.F du Plessis',
 'info.registry.people.Harbhajan Singh',
 'info.registry.people.J Suchith',
 'info.registry.people.LMP Simmons',
 'info.registry.people.MEK Hussey',
 'info.registry.people.MJ McClenaghan',
 'info.registry.people.MM Sharma',
 'info.registry.people.P Negi',
 'info.registry.people.PA Patel',
 'info.registry.people.R Vinay Kumar',
 'info.registry.people.RK Illingworth',
 'info.registry.people.RS Madugalle',
 'info.registry.people.SL Malinga',
 'info.registry.people.UBT Chand',
 'info.registry.people.VA Kulkarni',
 'info.outcome.method',
 'info.players.Delhi Daredevils',
 'info.players.Kings XI Punjab',
 'info.registry.people.A Mishra',
 'info.registry.people.AV Jayaprakash',
 'info.registry.people.BG Jerling',
 'info.registry.people.CH Lloyd',
 'info.registry.people.DPMD Jayawardene',
 'info.registry.people.G Gambhir',
 'info.registry.people.GD McGrath',
 'info.registry.people.IK Pathan',
 'info.registry.people.JR Hopes',
 'info.registry.people.KD Karthik',
 'info.registry.people.LA Pomersbach',
 'info.registry.people.MF Maharoof',
 'info.registry.people.PJ Sangwan',
 'info.registry.people.PP Chawla',
 'info.registry.people.R Bhatia',
 'info.registry.people.RE Koertzen',
 'info.registry.people.RR Powar',
 'info.registry.people.S Sreesanth',
 'info.registry.people.SE Marsh',
 'info.registry.people.Shoaib Malik',
 'info.registry.people.TM Dilshan',
 'info.registry.people.U Kaul',
 'info.registry.people.V Sehwag',
 'info.registry.people.VRV Singh',
 'info.registry.people.Yuvraj Singh',
 'info.players.Kochi Tuskers Kerala',
 'info.registry.people.AA Chavan',
 'info.registry.people.AL Menaria',
 'info.registry.people.BB McCullum',
 'info.registry.people.BJ Hodge',
 'info.registry.people.FY Fazal',
 'info.registry.people.ND Doshi',
 'info.registry.people.OA Shah',
 'info.registry.people.P Parameswaran',
 'info.registry.people.P Prasanth',
 'info.registry.people.PR Reiffel',
 'info.registry.people.PR Shah',
 'info.registry.people.R Dravid',
 'info.registry.people.RJ Tucker',
 'info.registry.people.RP Singh',
 'info.registry.people.RS Mahanama',
 'info.registry.people.S Asnani',
 'info.registry.people.SR Watson',
 'info.registry.people.SW Tait',
 'info.registry.people.Y Gnaneswara Rao',
 'info.players.Royal Challengers Bangalore',
 'info.registry.people.AB de Villiers',
 'info.registry.people.AJ Pycroft',
 'info.registry.people.BNJ Oxenford',
 'info.registry.people.C Shamshuddin',
 'info.registry.people.CH Gayle',
 'info.registry.people.DA Warner',
 'info.registry.people.LRPL Taylor',
 'info.registry.people.MA Agarwal',
 'info.registry.people.R Risodkar',
 'info.registry.people.V Kohli',
 'info.registry.people.VR Aaron',
 'info.registry.people.Y Venugopal Rao',
 'info.registry.people.Z Khan',
 'info.registry.people.BCJ Cutting',
 'info.registry.people.BK Ravi',
 'info.registry.people.CA Ingram',
 'info.registry.people.I Sharma',
 'info.registry.people.KMA Paul',
 'info.registry.people.M Nayyar',
 'info.registry.people.R Tewatia',
 'info.registry.people.Rasikh Salam',
 'info.registry.people.S Ravi',
 'info.registry.people.YC Barde',
 'info.players.Gujarat Titans',
 'info.registry.people.A Manohar',
 'info.registry.people.AS Joseph',
 'info.registry.people.CB Gaffaney',
 'info.registry.people.DA Miller',
 'info.registry.people.GR Sadashiv Iyer',
 'info.registry.people.J Madanagopal',
 'info.registry.people.KS Williamson',
 'info.registry.people.LH Ferguson',
 'info.registry.people.M Jansen',
 'info.registry.people.Mohammed Shami',
 'info.registry.people.N Pooran',
 'info.registry.people.Rashid Khan',
 'info.registry.people.Shubman Gill',
 'info.registry.people.Umran Malik',
 'info.registry.people.WP Saha',
 'info.registry.people.Washington Sundar',
 'info.registry.people.Yash Dayal',
 'info.players.Rising Pune Supergiants',
 'info.registry.people.Ankit Sharma',
 'info.registry.people.GJ Maxwell',
 'info.registry.people.KJ Abbott',
 'info.registry.people.KP Pietersen',
 'info.registry.people.M Ashwin',
 'info.registry.people.M Vohra',
 'info.registry.people.NLTC Perera',
 'info.registry.people.P Sahu',
 'info.registry.people.Sandeep Sharma',
 'info.registry.people.Basil Thampi',
 'info.registry.people.D Brevis',
 'info.registry.people.Ishan Kishan',
 'info.registry.people.KN Ananthapadmanabhan',
 'info.registry.people.LS Livingstone',
 'info.registry.people.M Shahrukh Khan',
 'info.registry.people.MV Saidharshan Kumar',
 'info.registry.people.OF Smith',
 'info.registry.people.RD Chahar',
 'info.registry.people.TS Mills',
 'info.registry.people.Tilak Varma',
 'info.registry.people.UV Gandhe',
 'info.registry.people.VG Arora',
 'info.registry.people.AM Nayar',
 'info.registry.people.BF Bowden',
 'info.registry.people.DJ Harper',
 'info.registry.people.DS Kulkarni',
 'info.registry.people.FM Engineer',
 'info.registry.people.GA Pratapkumar',
 'info.registry.people.Joginder Sharma',
 'info.registry.people.L Ronchi',
 'info.registry.people.MA Khote',
 'info.registry.people.MS Gony',
 'info.registry.people.P Amarnath',
 'info.registry.people.RV Uthappa',
 'info.registry.people.SM Pollock',
 'info.registry.people.ST Jayasuriya',
 'info.registry.people.VS Yeligati',
 'info.registry.people.BW Hilfenhaus',
 'info.registry.people.GF Labrooy',
 'info.registry.people.IC Pandey',
 'info.registry.people.JP Faulkner',
 'info.registry.people.K Srinivasan',
 'info.registry.people.M Manhas',
 'info.registry.people.PV Tambe',
 'info.registry.people.STR Binny',
 'info.registry.people.SV Samson',
 'info.registry.people.TG Southee',
 'info.registry.people.B Sai Sudharsan',
 'info.registry.people.DL Chahar',
 'info.registry.people.JC Buttler',
 'info.registry.people.M Prasidh Krishna',
 'info.registry.people.MJ Santner',
 'info.registry.people.Mohammed Siraj',
 'info.registry.people.Mujeeb Ur Rahman',
 'info.registry.people.Naman Dhir',
 'info.registry.people.PVSN Raju',
 'info.registry.people.Prakash Bhatt',
 'info.registry.people.R Minz',
 'info.registry.people.R Sai Kishore',
 'info.registry.people.RD Rickelton',
 'info.registry.people.SE Rutherford',
 'info.registry.people.TM Srivastava',
 'info.registry.people.Vinod Seshan',
 'info.registry.people.A Chopra',
 'info.registry.people.AB Dinda',
 'info.registry.people.D Govindjee',
 'info.registry.people.EC Hendrikse',
 'info.registry.people.K Goel',
 'info.registry.people.KC Sangakkara',
 'info.registry.people.LR Shukla',
 'info.registry.people.M Kartik',
 'info.registry.people.MC Henriques',
 'info.registry.people.RS Bopara',
 'info.registry.people.SC Ganguly',
 'info.registry.people.SD Ranade',
 'info.registry.people.T Kohli',
 'info.registry.people.TH Wijewardene',
 'info.registry.people.VS Malik',
 'info.registry.people.YA Abdulla',
 'info.registry.people.Yashpal Singh',
 'info.registry.people.AB Agarkar',
 'info.registry.people.CJ McKay',
 'info.registry.people.DJ Jacobs',
 'info.registry.people.M Morkel',
 'info.registry.people.MM Patel',
 'info.registry.people.PG Pathak',
 'info.registry.people.PP Ojha',
 'info.registry.people.RE Levi',
 'info.registry.people.S Nadeem',
 'info.registry.people.SK Tarapore',
 'info.registry.people.Y Nagar',
 'info.players.Royal Challengers Bengaluru',
 'info.registry.people.Abhijit Bhattacharya',
 'info.registry.people.Aniket Verma',
 'info.registry.people.E Malinga',
 'info.registry.people.Harsh Dubey',
 'info.registry.people.K Swaroopanand',
 'info.registry.people.L Ngidi',
 'info.registry.people.P Dharmani',
 'info.registry.people.PD Salt',
 'info.registry.people.R Shepherd',
 'info.registry.people.RM Patidar',
 'info.registry.people.TH David',
 'info.registry.people.D Padikkal',
 'info.registry.people.DJ Mitchell',
 'info.registry.people.DR Sams',
 'info.registry.people.HR Shokeen',
 'info.registry.people.K Kartikeya',
 'info.registry.people.KR Sen',
 'info.registry.people.R Parag',
 'info.registry.people.RP Meredith',
 'info.registry.people.YS Chahal',
 'info.registry.people.Aleem Dar',
 'info.registry.people.JDS Neesham',
 'info.registry.people.JP Duminy',
 'info.registry.people.K Bharatan',
 'info.registry.people.MA Starc',
 'info.registry.people.MK Tiwary',
 'info.registry.people.NJ Maddinson',
 'info.registry.people.R Sharma',
 'info.registry.people.S Rana',
 'info.registry.people.WD Parnell',
 'info.outcome.eliminator',
 'info.outcome.result',
 'info.registry.people.AD Mascarenhas',
 'info.registry.people.Anureet Singh',
 'info.registry.people.BAW Mendis',
 'info.registry.people.GR Viswanath',
 'info.registry.people.Kamran Khan',
 'info.registry.people.M Erasmus',
 'info.registry.people.M Rawat',
 'info.registry.people.MR Benson',
 'info.registry.people.PC Valthaty',
 'info.registry.people.RJ Quiney',
 'info.registry.people.SB Bangar',
 'info.players.Lucknow Super Giants',
 'info.registry.people.A Badoni',
 'info.registry.people.DS Rathi',
 'info.registry.people.M Siddharth',
 'info.registry.people.MP Stoinis',
 'info.registry.people.MR Marsh',
 'info.registry.people.N Wadhera',
 'info.registry.people.Priyansh Arya',
 'info.registry.people.Ravi Bishnoi',
 'info.registry.people.SN Thakur',
 'info.registry.people.Suryansh Shedge',
 'info.registry.people.B Lee',
 'info.registry.people.EJG Morgan',
 'info.registry.people.Iqbal Abdulla',
 'info.registry.people.JH Kallis',
 'info.registry.people.KM Jadhav',
 'info.registry.people.MS Bisla',
 'info.registry.people.RB Tiffin',
 'info.registry.people.RV Gomez',
 'info.registry.people.S Das',
 'info.registry.people.SS Hazare',
 'info.registry.people.Shakib Al Hasan',
 'info.registry.people.DJ Hooda',
 'info.registry.people.J Theron',
 'info.registry.people.KK Nair',
 'info.players.Pune Warriors',
 'info.registry.people.AC Thomas',
 'info.registry.people.AD Mathews',
 'info.registry.people.Asad Rauf',
 'info.registry.people.JD Ryder',
 'info.registry.people.MK Pandey',
 'info.registry.people.S Dua',
 'info.players.Deccan Chargers',
 'info.registry.people.AA Bilakhia',
 'info.registry.people.AC Gilchrist',
 'info.registry.people.DL Vettori',
 'info.registry.people.DP Nannes',
 'info.registry.people.FH Edwards',
 'info.registry.people.HH Gibbs',
 'info.registry.people.JD Cloete',
 'info.registry.people.Shoaib Ahmed',
 'info.registry.people.TL Suman',
 'info.registry.people.A Totre',
 'info.registry.people.A Zampa',
 'info.registry.people.Dhruv Jurel',
 'info.registry.people.JO Holder',
 'info.registry.people.K Yadav',
 'info.registry.people.Mohamad Rafi',
 'info.registry.people.YBK Jaiswal',
 'info.registry.people.KL Rahul',
 'info.registry.people.MJ Henry',
 'info.registry.people.Mohsin Khan',
 'info.registry.people.Mustafizur Rahman',
 'info.registry.people.Sanjay Verma',
 'info.registry.people.Yash Thakur',
 'info.registry.people.GS Sandhu',
 'info.registry.people.RM Deshpande',
 'info.registry.people.A Kamboj',
 'info.registry.people.DS Manohar',
 'info.registry.people.Harshit Rana',
 'info.registry.people.N Thushara',
 'info.registry.people.Ramandeep Singh',
 'info.registry.people.AF Milne',
 'info.registry.people.AY Dandekar',
 'info.registry.people.Anmolpreet Singh',
 'info.registry.people.JR Hazlewood',
 'info.registry.people.K Gowtham',
 'info.registry.people.A Kumble',
 'info.registry.people.AS Yadav',
 'info.registry.people.B Chipli',
 'info.registry.people.BR Doctrove',
 'info.registry.people.DP Vijaykumar',
 'info.registry.people.DW Steyn',
 'info.registry.people.MV Boucher',
 'info.registry.people.Misbah-ul-Haq',
 'info.registry.people.P Kumar',
 'info.registry.people.SB Styris',
 'info.registry.people.SL Shastri',
 'info.registry.people.Shahid Afridi',
 'info.registry.people.Talat Ali',
 'info.registry.people.VVS Laxman',
 'info.registry.people.W Jaffer',
 'info.registry.people.RE van der Merwe',
 'info.registry.people.S Anirudha',
 'info.registry.people.A Ashish Reddy',
 'info.registry.people.A Deshmukh',
 'info.registry.people.BB Sran',
 'info.registry.people.Bipul Sharma',
 'info.registry.people.MJ Guptill',
 'info.registry.people.AJ Tye',
 'info.registry.people.D Pretorius',
 'info.registry.people.E Lewis',
 'info.registry.people.Mukesh Choudhary',
 'info.registry.people.PVD Chameera',
 'info.registry.people.AT Holdstock',
 'info.registry.people.Anish Sahasrabudhe',
 'info.registry.people.D Madushanka',
 'info.registry.people.Kuldeep Yadav',
 'info.registry.people.Mukesh Kumar',
 'info.registry.people.P Nissanka',
 'info.registry.people.S Arora',
 'info.registry.people.Sakib Hussain',
 'info.registry.people.Sameer Rizvi',
 'info.registry.people.Shivang Kumar',
 'info.registry.people.T Stubbs',
 'info.registry.people.A Nand Kishore',
 'info.registry.people.AJ Turner',
 'info.registry.people.BA Stokes',
 'info.registry.people.CH Morris',
 'info.registry.people.JC Archer',
 'info.registry.people.K Srinath',
 'info.registry.people.S Gopal',
 'info.registry.people.CA Lynn',
 'info.registry.people.CA Pujara',
 'info.registry.people.GJ Bailey',
 'info.registry.people.MG Johnson',
 'info.registry.people.R Dhawan',
 'info.registry.people.C de Grandhomme',
 'info.registry.people.M Markande',
 'info.registry.people.Navdeep Saini',
 'info.registry.people.A Choudhary',
 'info.registry.people.CJ Jordan',
 'info.registry.people.Mandeep Singh',
 'info.registry.people.N Pandit',
 'info.registry.people.NJ Llong',
 'info.registry.people.S Aravind',
 'info.registry.people.Sachin Baby',
 'info.registry.people.Fazalhaq Farooqi',
 'info.registry.people.NT Ellis',
 'info.registry.people.PK Garg',
 'info.registry.people.PN Mankad',
 'info.registry.people.AS Rajpoot',
 'info.registry.people.Azhar Mahmood',
 'info.registry.people.DJ Hussey',
 'info.registry.people.Gurkeerat Singh',
 'info.registry.people.P Awana',
 'info.registry.people.R Sathish',
 'info.registry.people.RJ Harris',
 'info.registry.people.KL Nagarkoti',
 'info.registry.people.Kartik Tyagi',
 'info.registry.people.Shivam Mavi',
 'info.registry.people.A Kripal Singh',
 'info.registry.people.Arshad Khan',
 'info.registry.people.Ashwani Kumar',
 'info.registry.people.C Bosch',
 'info.registry.people.G Coetzee',
 'info.registry.people.KM Gandhi',
 'info.registry.people.KV Sharma',
 'info.registry.people.M Krishnadas',
 'info.registry.people.WG Jacks',
 'info.registry.people.Mohammad Nabi',
 'info.registry.people.S Kaul',
 'info.registry.people.RR Rossouw',
 'info.registry.people.SN Khan',
 'info.registry.people.DH Yagnik',
 'info.registry.people.Harpreet Singh',
 'info.registry.people.J Botha',
 'info.registry.people.JE Taylor',
 'info.registry.people.NL McCullum',
 'info.registry.people.R Subramanian',
 'info.registry.people.SJA Taufel',
 'info.registry.people.AA Jhunjhunwala',
 'info.registry.people.DE Bollinger',
 'info.registry.people.MJ Lumb',
 'info.registry.people.S Narwal',
 'info.registry.people.SB Wagh',
 'info.registry.people.AU Rashid',
 'info.registry.people.GD Phillips',
 'info.registry.people.HC Brook',
 'info.registry.people.KM Asif',
 'info.registry.people.NA Saini',
 'info.registry.people.R Pandit',
 'info.registry.people.Lalit Yadav',
 'info.registry.people.S Lamichhane',
 'info.registry.people.SW Billings',
 'info.registry.people.V Shankar',
 'info.registry.people.Ashok Sharma',
 'info.registry.people.D Ferreira',
 'info.registry.people.Kumar Kushagra',
 'info.registry.people.N Burger',
 'info.registry.people.V Suryavanshi',
 'info.registry.people.M Kuppuraj',

In [10]:

feature_cols = ["innings", "info.teams", 'info.city',"match_id"]

final_df = final_df[feature_cols]


final_df

,innings,info.teams,info.city,match_id
0,"[{'team': 'Sunrisers Hyderabad', 'overs': [{'o...","[Sunrisers Hyderabad, Punjab Kings]",Mohali,1
1,"[{'team': 'Chennai Super Kings', 'overs': [{'o...","[Chennai Super Kings, Kolkata Knight Riders]",Kolkata,2
2,"[{'team': 'Rajasthan Royals', 'overs': [{'over...","[Chennai Super Kings, Rajasthan Royals]",Kimberley,3
3,"[{'team': 'Mumbai Indians', 'overs': [{'over':...","[Mumbai Indians, Delhi Capitals]",Sharjah,4
4,"[{'team': 'Mumbai Indians', 'overs': [{'over':...","[Chennai Super Kings, Mumbai Indians]",Mumbai,5
...,...,...,...,...
1228,"[{'team': 'Royal Challengers Bangalore', 'over...","[Royal Challengers Bangalore, Chennai Super Ki...",NaN,1229
1229,"[{'team': 'Rajasthan Royals', 'overs': [{'over...","[Rajasthan Royals, Kolkata Knight Riders]",Jaipur,1230
1230,"[{'team': 'Royal Challengers Bangalore', 'over...","[Chennai Super Kings, Royal Challengers Bangal...",Chennai,1231
1231,"[{'team': 'Delhi Daredevils', 'overs': [{'over...","[Delhi Daredevils, Sunrisers Hyderabad]",Hyderabad,1232
1232,"[{'team': 'Chennai Super Kings', 'overs': [{'o...","[Chennai Super Kings, Punjab Kings]",Chennai,1233

In [21]:
retain_city = [
    "Mohali",
    "Kolkata",
    "Mumbai",
    "Delhi",
    "Pune",
    "Chennai",
    "Ahmedabad",
    "Lucknow",
    "Jaipur",
    "Raipur",
    "Hyderabad",
    "Bengaluru",
    "Chandigarh",
    "Visakhapatnam",
    "Dharamsala",
    "Ranchi",
]

retain_cities = set(retain_city)

final_df = final_df[final_df["info.city"].isin(retain_cities)]

team_mapping = {
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru",
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings",
    "Rising Pune Supergiant": "Rising Pune Supergiants",
}

final_df["info.teams"] = final_df["info.teams"].apply(
    lambda teams: [team_mapping.get(team, team) for team in teams]
)

teams_to_remove = [
    "Rising Pune Supergiant",
    "Rising Pune Supergiants",
    "Kochi Tuskers Kerala",
    "Deccan Chargers",
    "Gujarat Lions",
    "Pune Warriors",
]

# Convert list to a set for faster lookup
remove_set = set(teams_to_remove)

# Keep rows where neither team in the 'info.teams' list intersects with our remove_set
final_df = final_df[
    ~final_df["info.teams"].apply(lambda teams: any(t in remove_set for t in teams))
]


def update_innings(innings):
    for inning in innings:
        inning["team"] = team_mapping.get(inning["team"], inning["team"])
    return innings

final_df["innings"] = final_df["innings"].apply(update_innings)


# Display the filtered dataframe
final_df

,innings,info.teams,info.city,match_id
0,"[{'team': 'Sunrisers Hyderabad', 'overs': [{'o...","[Sunrisers Hyderabad, Punjab Kings]",Mohali,1
1,"[{'team': 'Chennai Super Kings', 'overs': [{'o...","[Chennai Super Kings, Kolkata Knight Riders]",Kolkata,2
4,"[{'team': 'Mumbai Indians', 'overs': [{'over':...","[Chennai Super Kings, Mumbai Indians]",Mumbai,5
5,"[{'team': 'Delhi Capitals', 'overs': [{'over':...","[Delhi Capitals, Punjab Kings]",Delhi,6
7,"[{'team': 'Royal Challengers Bengaluru', 'over...","[Delhi Capitals, Royal Challengers Bengaluru]",Delhi,8
...,...,...,...,...
1227,"[{'team': 'Kolkata Knight Riders', 'overs': [{...","[Mumbai Indians, Kolkata Knight Riders]",Mumbai,1228
1229,"[{'team': 'Rajasthan Royals', 'overs': [{'over...","[Rajasthan Royals, Kolkata Knight Riders]",Jaipur,1230
1230,"[{'team': 'Royal Challengers Bengaluru', 'over...","[Chennai Super Kings, Royal Challengers Bengal...",Chennai,1231
1231,"[{'team': 'Delhi Capitals', 'overs': [{'over':...","[Delhi Capitals, Sunrisers Hyderabad]",Hyderabad,1232
1232,"[{'team': 'Chennai Super Kings', 'overs': [{'o...","[Chennai Super Kings, Punjab Kings]",Chennai,1233

In [22]:
final_df

,innings,info.teams,info.city,match_id
0,"[{'team': 'Sunrisers Hyderabad', 'overs': [{'o...","[Sunrisers Hyderabad, Punjab Kings]",Mohali,1
1,"[{'team': 'Chennai Super Kings', 'overs': [{'o...","[Chennai Super Kings, Kolkata Knight Riders]",Kolkata,2
4,"[{'team': 'Mumbai Indians', 'overs': [{'over':...","[Chennai Super Kings, Mumbai Indians]",Mumbai,5
5,"[{'team': 'Delhi Capitals', 'overs': [{'over':...","[Delhi Capitals, Punjab Kings]",Delhi,6
7,"[{'team': 'Royal Challengers Bengaluru', 'over...","[Delhi Capitals, Royal Challengers Bengaluru]",Delhi,8
...,...,...,...,...
1227,"[{'team': 'Kolkata Knight Riders', 'overs': [{...","[Mumbai Indians, Kolkata Knight Riders]",Mumbai,1228
1229,"[{'team': 'Rajasthan Royals', 'overs': [{'over...","[Rajasthan Royals, Kolkata Knight Riders]",Jaipur,1230
1230,"[{'team': 'Royal Challengers Bengaluru', 'over...","[Chennai Super Kings, Royal Challengers Bengal...",Chennai,1231
1231,"[{'team': 'Delhi Capitals', 'overs': [{'over':...","[Delhi Capitals, Sunrisers Hyderabad]",Hyderabad,1232
1232,"[{'team': 'Chennai Super Kings', 'overs': [{'o...","[Chennai Super Kings, Punjab Kings]",Chennai,1233

In [23]:
first_innings = final_df.iloc[1]['innings'][0]

for items in first_innings:
        batting_team = first_innings['team']
        overs = first_innings['overs']
        for over in overs:
            print(over)

{'over': 0, 'deliveries': [{'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'UT Yadav', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 1, 'deliveries': [{'batter': 'RD Gaikwad', 'bowler': 'D Wiese', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'RD Gaikwad', 'bowler': 'D Wiese', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 2, 'deliveries': [{'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'UT Yadav', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'UT Yadav', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'UT Yadav', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}
{'over': 3, 'deliveries': [{'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 4, 'deliveries': [{'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 5, 'deliveries': [{'batter': 'RD Gaikwad', 'bowler': 'K Khejroliya', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'K Khejroliya', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DP Conway', 'bowler': 'K Khejroliya', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'RD Gaikwad', 'bowler': 'K Khejroliya', 'non_striker': 'DP Conway', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'RD Gaikwad', 'bowler': 'K Khejroliya', 'non_striker': 'DP Conway', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'RD Gaikwad', 'bowler': 'K Khejroliya', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 6, 'deliveries': [{'batter': 'DP Conway', 'bowler': 'SP Narine', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'RD Gaikwad', 'bowler': 'SP Narine', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'SP Narine', 'non_striker': 'DP Conway', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'RD Gaikwad', 'bowler': 'SP Narine', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'SP Narine', 'non_striker': 'DP Conway', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'RD Gaikwad', 'bowler': 'SP Narine', 'non_striker': 'DP Conway', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}
{'over': 7, 'deliveries': [{'batter': 'DP Conway', 'bowler': 'Suyash Sharma', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'Suyash Sharma', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'RD Gaikwad', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'player_out': 'RD Gaikwad', 'kind': 'bowled'}]}, {'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}
{'over': 8, 'deliveries': [{'batter': 'DP Conway', 'bowler': 'SP Narine', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'SP Narine', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'SP Narine', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'SP Narine', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'SP Narine', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'SP Narine', 'non_striker': 'AM Rahane', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}
{'over': 9, 'deliveries': [{'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'DP Conway', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 10, 'deliveries': [{'batter': 'AM Rahane', 'bowler': 'CV Varun', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'CV Varun', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 11, 'deliveries': [{'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'review': {'by': 'Kolkata Knight Riders', 'umpire': 'Tapan Sharma', 'batter': 'AM Rahane', 'decision': 'struck down', 'type': 'wicket', 'umpires_call': True}, 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 12, 'deliveries': [{'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'player_out': 'DP Conway', 'fielders': [{'name': 'D Wiese'}], 'kind': 'caught'}]}, {'batter': 'S Dube', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dube', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'CV Varun', 'non_striker': 'S Dube', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dube', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'S Dube', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}
{'over': 13, 'deliveries': [{'batter': 'AM Rahane', 'bowler': 'UT Yadav', 'non_striker': 'S Dube', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'AM Rahane', 'bowler': 'UT Yadav', 'non_striker': 'S Dube', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'AM Rahane', 'bowler': 'UT Yadav', 'non_striker': 'S Dube', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'AM Rahane', 'bowler': 'UT Yadav', 'non_striker': 'S Dube', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dube', 'bowler': 'UT Yadav', 'non_striker': 'AM Rahane', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'S Dube', 'bowler': 'UT Yadav', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 14, 'deliveries': [{'batter': 'S Dube', 'bowler': 'D Wiese', 'non_striker': 'AM Rahane', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'S Dube', 'bowler': 'D Wiese', 'non_striker': 'AM Rahane', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'S Dube', 'bowler': 'D Wiese', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'D Wiese', 'non_striker': 'S Dube', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dube', 'bowler': 'D Wiese', 'non_striker': 'AM Rahane', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'S Dube', 'bowler': 'D Wiese', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 15, 'deliveries': [{'batter': 'S Dube', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dube', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'S Dube', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dube', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'Suyash Sharma', 'non_striker': 'S Dube', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dube', 'bowler': 'Suyash Sharma', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 16, 'deliveries': [{'batter': 'S Dube', 'bowler': 'AD Russell', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'AD Russell', 'non_striker': 'S Dube', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'AM Rahane', 'bowler': 'AD Russell', 'extras': {'wides': 1}, 'non_striker': 'S Dube', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'AD Russell', 'non_striker': 'S Dube', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dube', 'bowler': 'AD Russell', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'AD Russell', 'extras': {'wides': 1}, 'non_striker': 'S Dube', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'AD Russell', 'non_striker': 'S Dube', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'AM Rahane', 'bowler': 'AD Russell', 'non_striker': 'S Dube', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}
{'over': 17, 'deliveries': [{'batter': 'S Dube', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'S Dube', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'S Dube', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'player_out': 'S Dube', 'fielders': [{'name': 'JJ Roy'}], 'kind': 'caught'}]}, {'batter': 'RA Jadeja', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RA Jadeja', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'K Khejroliya', 'non_striker': 'RA Jadeja', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}
{'over': 18, 'deliveries': [{'batter': 'RA Jadeja', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'RA Jadeja', 'bowler': 'CV Varun', 'non_striker': 'AM Rahane', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AM Rahane', 'bowler': 'CV Varun', 'non_striker': 'RA Jadeja', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'AM Rahane', 'bowler': 'CV Varun', 'non_striker': 'RA Jadeja', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'AM Rahane', 'bowler': 'CV Varun', 'non_striker': 'RA Jadeja', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'AM Rahane', 'bowler': 'CV Varun', 'non_striker': 'RA Jadeja', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}
{'over': 19, 'deliveries': [{'batter': 'RA Jadeja', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'RA Jadeja', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'RA Jadeja', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'RA Jadeja', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'player_out': 'RA Jadeja', 'fielders': [{'name': 'RK Singh'}], 'kind': 'caught'}]}, {'batter': 'MS Dhoni', 'bowler': 'K Khejroliya', 'extras': {'noballs': 1}, 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'MS Dhoni', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'MS Dhoni', 'bowler': 'K Khejroliya', 'non_striker': 'AM Rahane', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}]}
{'over': 0, 'deliveries': [{'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'UT Yadav', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 1, 'deliveries': [{'batter': 'RD Gaikwad', 'bowler': 'D Wiese', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'RD Gaikwad', 'bowler': 'D Wiese', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'DP Conway', 'bowler': 'D Wiese', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 2, 'deliveries': [{'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DP Conway', 'bowler': 'UT Yadav', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'UT Yadav', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'UT Yadav', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'RD Gaikwad', 'bowler': 'UT Yadav', 'non_striker': 'DP Conway', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}
{'over': 3, 'deliveries': [{'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'DP Conway', 'bowler': 'CV Varun', 'non_striker': 'RD Gaikwad', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}

In [25]:
delivery_df = pd.DataFrame()

for index, row in final_df.iterrows():
    first_innings = row["innings"][0]
    city = row['info.city']
    mtch_id = row['match_id']
    teams = row['info.teams']
    for items in first_innings:
        team = first_innings['team']
        overs = first_innings['overs']

        match_id = []
        cities = []
        batting_team = []
        bowling_team = []
        runs = []
        current_score = []
        current_run_rate = []
        balls_left = []
        total_runs = 0
        player_of_dismissed = []
        for single_over in overs:
            over = single_over['over']
            for idx, delivery in enumerate(single_over['deliveries']):
                match_id.append(mtch_id)
                cities.append(city)
                batting_team.append(team)
                runs.append(int(delivery['runs']['total']))
                bowling_team.append([t for t in teams if t != team][0])  # Assuming the other team is the bowling team
                balls_left.append(120 - ((over * 6)+ idx + 1))

                if delivery['runs']['total'] > 0:
                    total_runs += int(delivery['runs']['total'])
                current_score.append(total_runs)
                current_run_rate.append(round((total_runs / (over+1)), 2))

                if 'wickets' in delivery:
                    player_of_dismissed.append(1)
                else:
                    player_of_dismissed.append(0)

    loop_df = pd.DataFrame({
            'match_id':match_id,
            'batting_team':batting_team,
            "bowling_team":bowling_team,
            "balls_left":balls_left,
            'current_score': current_score,
            "current_run_rate": current_run_rate,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':cities
    })

    delivery_df = pd.concat([delivery_df, loop_df], ignore_index=True)

delivery_df

# delivery_df.to_csv('delivery_data.csv', index=False)

,match_id,batting_team,bowling_team,balls_left,current_score,current_run_rate,runs,player_dismissed,city
0,1,Sunrisers Hyderabad,Punjab Kings,119,0,0.00,0,0,Mohali
1,1,Sunrisers Hyderabad,Punjab Kings,118,0,0.00,0,0,Mohali
2,1,Sunrisers Hyderabad,Punjab Kings,117,4,4.00,4,0,Mohali
3,1,Sunrisers Hyderabad,Punjab Kings,116,4,4.00,0,0,Mohali
4,1,Sunrisers Hyderabad,Punjab Kings,115,4,4.00,0,0,Mohali
...,...,...,...,...,...,...,...,...,...
100192,1233,Chennai Super Kings,Punjab Kings,7,186,9.79,0,1,Chennai
100193,1233,Chennai Super Kings,Punjab Kings,6,186,9.79,0,1,Chennai
100194,1233,Chennai Super Kings,Punjab Kings,5,186,9.79,0,1,Chennai
100195,1233,Chennai Super Kings,Punjab Kings,5,190,9.50,4,0,Chennai
100196,1233,Chennai Super Kings,Punjab Kings,4,190,9.50,0,1,Chennai

In [15]:
# total_runs = delivery_df.groupby('match_id').sum()['runs'].reset_index()

total_runs = delivery_df.groupby("match_id")["runs"].sum().reset_index(name="total_runs")

delivery_df = delivery_df.merge(total_runs, on="match_id", how="left")

# delivery_df.drop(columns=['total_runs_x', "total_runs_y"], inplace=True)

delivery_df

,match_id,batting_team,bowling_team,balls_left,current_score,current_run_rate,runs,player_dismissed,city,total_runs
0,1,Sunrisers Hyderabad,Punjab Kings,119,0,0.00,0,0,Mohali,182
1,1,Sunrisers Hyderabad,Punjab Kings,118,0,0.00,0,0,Mohali,182
2,1,Sunrisers Hyderabad,Punjab Kings,117,4,4.00,4,0,Mohali,182
3,1,Sunrisers Hyderabad,Punjab Kings,116,4,4.00,0,0,Mohali,182
4,1,Sunrisers Hyderabad,Punjab Kings,115,4,4.00,0,0,Mohali,182
...,...,...,...,...,...,...,...,...,...,...
100192,1233,Chennai Super Kings,Punjab Kings,7,186,9.79,0,1,Chennai,190
100193,1233,Chennai Super Kings,Punjab Kings,6,186,9.79,0,1,Chennai,190
100194,1233,Chennai Super Kings,Punjab Kings,5,186,9.79,0,1,Chennai,190
100195,1233,Chennai Super Kings,Punjab Kings,5,190,9.50,4,0,Chennai,190
100196,1233,Chennai Super Kings,Punjab Kings,4,190,9.50,0,1,Chennai,190

In [16]:
# print(delivery_df["player_dismissed"].dtype)
# print(delivery_df["player_dismissed"].unique()[:10])

delivery_df["wickets_fallen"] = (
    delivery_df.groupby("match_id")["player_dismissed"]
    .cumsum()
)

delivery_df["wickets_left"] = 10 - delivery_df["wickets_fallen"]

delivery_df.drop(columns=["player_dismissed", "wickets_fallen"], inplace=True)

delivery_df

,match_id,batting_team,bowling_team,balls_left,current_score,current_run_rate,runs,city,total_runs,wickets_left
0,1,Sunrisers Hyderabad,Punjab Kings,119,0,0.00,0,Mohali,182,10
1,1,Sunrisers Hyderabad,Punjab Kings,118,0,0.00,0,Mohali,182,10
2,1,Sunrisers Hyderabad,Punjab Kings,117,4,4.00,4,Mohali,182,10
3,1,Sunrisers Hyderabad,Punjab Kings,116,4,4.00,0,Mohali,182,10
4,1,Sunrisers Hyderabad,Punjab Kings,115,4,4.00,0,Mohali,182,10
...,...,...,...,...,...,...,...,...,...,...
100192,1233,Chennai Super Kings,Punjab Kings,7,186,9.79,0,Chennai,190,3
100193,1233,Chennai Super Kings,Punjab Kings,6,186,9.79,0,Chennai,190,2
100194,1233,Chennai Super Kings,Punjab Kings,5,186,9.79,0,Chennai,190,1
100195,1233,Chennai Super Kings,Punjab Kings,5,190,9.50,4,Chennai,190,1
100196,1233,Chennai Super Kings,Punjab Kings,4,190,9.50,0,Chennai,190,0

In [17]:

delivery_df["last_5_overs_runs"] = (
    delivery_df.groupby("match_id")["runs"]
    .transform(lambda x: x.rolling(30).sum())
)


# delivery_df['last_five'] = last_five

delivery_df.dropna(inplace=True)

delivery_df.count()

match_id             76685
batting_team         76685
bowling_team         76685
balls_left           76685
current_score        76685
current_run_rate     76685
runs                 76685
city                 76685
total_runs           76685
wickets_left         76685
last_5_overs_runs    76685
dtype: int64

In [18]:
delivery_df["city"].drop_duplicates().to_csv(
    "venue.csv",
    index=False,
    header=["city"]
)

In [19]:
delivery_df.to_csv("../../data/match_summary.csv", index=False)